spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_food_bd
    username: root
    password: sunethramc123

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


stripe:
  secret-key: sk_test_51Q7weM1ypTo0TJw9p5KuYGDDJJ2z5bWdfArkctGYBN4LeeMYwmpKgmaqRSkhyLXdmcipOlWRHrPVRkxzUyn60Ahm00WuqkpKKB